env:
  GITHUB_TOKEN:       ${{ secrets.GITHUB_TOKEN }}

name: CreateOrUpdateRelease
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Module Version in Environment Variable
      shell: pwsh
      run: |
        $ModuleVersion = [version](Import-PowerShellDataFile '.\Source\AzBobbyTables.PS\Manifest\AzBobbyTables.psd1').ModuleVersion
        $BumpedVersion = "$($ModuleVersion.Major).$($ModuleVersion.Minor).$($ModuleVersion.Build + 1)"
        "RELEASE_VERSION=$BumpedVersion" >> $env:GITHUB_ENV

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_VERSION }}
        draft: true
