env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: PublishReleaseAndModule
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get changelog
      id: get-changelog
      uses: release-flow/keep-a-changelog-action@v2
      with:
        command: query
        version: unreleased

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        name: ${{ github.ref }}
        draft: true
        body: ${{ steps.get-changelog.outputs.release-notes }}

    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        tag: ${{ github.ref }}
