env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: PublishReleaseAndModule
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 2

    - name: Get changelog
      id: get-changelog
      uses: release-flow/keep-a-changelog-action@v2
      with:
        command: query
        version: unreleased

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.ref_name }}
        draft: true
        body: ${{ steps.get-changelog.outputs.release-notes }}

    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        tag: ${{ github.ref }}

    - name: Push changelog
      run: |
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

        git add CHANGELOG.md
        git commit -m "docs: Update changelog for ${{ github.ref_name }}"
        git push origin main